services:
    _defaults:
        public: false

    ########### Vendor services
    CoderCat\JWKToPEM\JWKConverter: ~

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    Lcobucci\JWT\Builder: ~

    Lcobucci\JWT\Parsing\Encoder: ~

    Lcobucci\JWT\Parser: ~

    Lcobucci\JWT\Signer:
        class: Lcobucci\JWT\Signer\Rsa\Sha256

    Nyholm\Psr7\Factory\Psr17Factory: ~

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
        arguments:
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'

    ########### Core lib services
    OAT\Library\Lti1p3Core\Security\Key\KeyChainFactory: ~

    OAT\Library\Lti1p3Core\Platform\PlatformFactory: ~

    OAT\Library\Lti1p3Core\Tool\ToolFactory: ~

    OAT\Library\Lti1p3Core\Registration\RegistrationFactory: ~

    OAT\Library\Lti1p3Core\Security\Nonce\NonceGeneratorInterface:
        class: OAT\Library\Lti1p3Core\Security\Nonce\NonceGenerator

    OAT\Library\Lti1p3Core\Message\Builder\MessageBuilder:
        arguments:
            - '@OAT\Library\Lti1p3Core\Security\Nonce\NonceGeneratorInterface'
            - '@Lcobucci\JWT\Builder'
            - '@Lcobucci\JWT\Signer'

    ########### Bundle services
    OAT\Library\Lti1p3Core\Security\Key\KeyChainRepositoryInterface:
        alias: OAT\Library\Lti1p3Core\Security\Key\KeyChainRepository

    OAT\Library\Lti1p3Core\Security\Nonce\NonceRepositoryInterface:
        alias: OAT\Bundle\Lti1p3Bundle\Repository\NonceRepository

    OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface:
        alias: OAT\Bundle\Lti1p3Bundle\Repository\RegistrationRepository

    OAT\Bundle\Lti1p3Bundle\DependencyInjection\Builder\KeyChainRepositoryBuilder:
        arguments: ['@OAT\Library\Lti1p3Core\Security\Key\KeyChainFactory']

    OAT\Bundle\Lti1p3Bundle\DependencyInjection\Builder\RegistrationRepositoryBuilder:
        arguments:
            - '@OAT\Library\Lti1p3Core\Security\Key\KeyChainFactory'
            - '@OAT\Library\Lti1p3Core\Platform\PlatformFactory'
            - '@OAT\Library\Lti1p3Core\Tool\ToolFactory'
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationFactory'

    OAT\Library\Lti1p3Core\Security\Jwks\Exporter\JwksExporter:
        arguments: ['@OAT\Library\Lti1p3Core\Security\Key\KeyChainRepositoryInterface']

    OAT\Library\Lti1p3Core\Security\Jwks\Fetcher\JwksFetcherInterface:
        class: OAT\Library\Lti1p3Core\Security\Jwks\Fetcher\JwksFetcher
        arguments:
            - '@GuzzleHttp\ClientInterface'
            - '@CoderCat\JWKToPEM\JWKConverter'

    OAT\Library\Lti1p3Core\Security\Oidc\Endpoint\OidcLoginInitiator:
        arguments:
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Nonce\NonceGeneratorInterface'
            - '@OAT\Library\Lti1p3Core\Message\Builder\MessageBuilder'

    OAT\Library\Lti1p3Core\Launch\Validator\LtiLaunchRequestValidator:
        arguments:
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Nonce\NonceRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Jwks\Fetcher\JwksFetcherInterface'
            - '@Lcobucci\JWT\Signer'

    OAT\Bundle\Lti1p3Bundle\Security\Firewall\LtiLaunchRequestAuthenticationListener:
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
            - '@Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'

    OAT\Bundle\Lti1p3Bundle\Security\Authentication\Provider\LtiLaunchRequestAuthenticationProvider:
        arguments: ['@OAT\Library\Lti1p3Core\Launch\Validator\LtiLaunchRequestValidator']

    OAT\Library\Lti1p3Core\Launch\Builder\LtiLaunchRequestBuilder:
        arguments: ['@OAT\Library\Lti1p3Core\Message\Builder\MessageBuilder']
        public: true

    OAT\Library\Lti1p3Core\Launch\Builder\OidcLaunchRequestBuilder:
        arguments: ['@OAT\Library\Lti1p3Core\Message\Builder\MessageBuilder']
        public: true

    ########### Endpoints
    OAT\Bundle\Lti1p3Bundle\Action\Jwks\JwksAction:
        arguments: ['@OAT\Library\Lti1p3Core\Security\Jwks\Exporter\JwksExporter']
        tags: ['controller.service_arguments']

    OAT\Bundle\Lti1p3Bundle\Action\Tool\OidcLoginInitiationAction:
        arguments:
            - '@Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Oidc\Endpoint\OidcLoginInitiator'
        tags: ['controller.service_arguments']

