os: linux
dist: xenial
language: php

jobs:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS=--prefer-lowest --prefer-stable
    - php: 7.3
    - php: 7.4
    - php: 8.0

before_script:
  - composer self-update && composer update --no-interaction $COMPOSER_FLAGS

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/psalm --shepherd

after_script:
  - ./vendor/bin/php-coveralls -v
